name: Run Tests and Lint

on: [push, pull_request]

jobs:
  build:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # false - продолжить остальные тесты, даже если один упал.
      matrix:
        # Определяем переменную python-version и список её значений
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install_deps
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint with Flake8
        id: lint
        run: |
          source venv/bin/activate
          # Проверка версии flake8
          echo "Using flake8 $(flake8 --version)"
          flake8 . --count --show-source --statistics

      - name: Run tests with pytest
        id: tests
        run: |
          source venv/bin/activate
          echo "Using python $(python --version)"
          echo "Using pytest $(pytest --version)"
          pytest

      # Отправка уведомления в Telegram при провале
      - name: Send Telegram message on failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }} # Получатель из секрета GitHub
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }} # Токен бота из секрета GitHub
          message: |
            Тесты или линтинг провалены!
            Репозиторий: ${{ github.repository }}
            Событие: ${{ github.event_name }}
            Коммит: ${{ github.sha }}
